language: ruby
dist: trusty
cache:
  bundler: true
  directories:
    - node_modules
sudo: required
script:
  - bundle exec bin/setup
  - bundle exec rake travis:ci
before_install:
  - sudo apt-get install qt5-default libqt5webkit5-dev xvfb gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
#after_failure:
#  - cat ./log/test.log
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - JASMINE=true
branches:
  only: # Only build master. Pull requests to master also get built.
    - master
deploy:
  provider: script
  script: bin/ecc-sync
  on:
    branch: master
    repo: nasa/earthdata-search
