language: ruby
dist: trusty
os: osx
cache:
  bundler: true
  directories:
    - node_modules
sudo: required
before_script:
#  - sudo apt-get install qt5-default libqt5webkit5-dev qtdeclarative5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
#  - echo '----------------------------------'
#  - qmake -v
#  - echo '----------------------------------'
#  - sudo apt-get install libglew-dev libcheese7 libcheese-gtk23 libclutter-gst-2.0-0 libcogl15 libclutter-gtk-1.0-0 libclutter-1.0-0
#  - sudo apt-get install gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3
script:
  - bundle exec bin/setup
  - bundle exec rake travis:ci
#after_failure:
#  - cat ./log/test.log
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - echo '---begin of qt-------------------------------'
  - brew install qt@5.5
#  - echo 'export PATH="$(brew --prefix qt@5.5)/bin:$PATH"' >> ~/.bashrc

  - brew link --force qt@5.5
  - which qmake
  - echo '---end of qt-------------------------------'
  - echo '---begin of openssl-------------------------------'
  - brew upgrade openssl
  - PKG_CONFIG_PATH=”$(brew —-prefix openssl)/lib/pkgconfig” gem install eventmachine -v '1.0.4'
  - echo '---begin of openssl-------------------------------'
#addons:
#  apt:
#    sources:
#      - ubuntu-sdk-team
#    packages:
#      - libqt5webkit5-dev
#      - qtdeclarative5-dev
#      - gstreamer1.0-plugins-base
#      - gstreamer1.0-tools
#      - gstreamer1.0-x
env:
  global:
    - CI_NODE_TOTAL=4
    - BUNDLE_JOBS=4
#    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
#    - QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
#    - JAVA_OPTS=-Djava.security.egd=file:/dev/urandom
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - JASMINE=true
branches:
  only: # Only build master. Pull requests to master also get built.
    - master
deploy:
  provider: script
  script: bin/ecc-sync
  on:
    branch: master
    repo: nasa/earthdata-search
